object CineMain: TCineMain
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'CineMain'
  ClientHeight = 981
  ClientWidth = 1568
  Color = clBtnFace
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  Position = poScreenCenter
  TextHeight = 15
  object PanelTopBar: TPanel
    Left = 0
    Top = 0
    Width = 1568
    Height = 25
    Align = alTop
    BevelOuter = bvNone
    Color = 6900229
    ParentBackground = False
    TabOrder = 0
  end
  object PanelTopTitle: TPanel
    Left = 0
    Top = 25
    Width = 1568
    Height = 64
    Align = alTop
    BevelOuter = bvNone
    Color = 4731908
    ParentBackground = False
    TabOrder = 1
    object Label1: TLabel
      Left = 747
      Top = 13
      Width = 74
      Height = 38
      Caption = 'Cine'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -32
      Font.Name = 'Georgia'
      Font.Style = [fsBold]
      ParentFont = False
    end
  end
  object PanelStatusBar: TPanel
    Left = 0
    Top = 946
    Width = 1568
    Height = 35
    Align = alBottom
    BevelOuter = bvNone
    Color = 4731908
    ParentBackground = False
    TabOrder = 2
  end
  object PanelDesktop: TPanel
    Left = 0
    Top = 89
    Width = 1568
    Height = 857
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 3
    object PanelButtons: TPanel
      Left = 0
      Top = 0
      Width = 224
      Height = 857
      Align = alLeft
      BevelOuter = bvNone
      TabOrder = 0
      ExplicitTop = -6
      object FecharButton: TStyledButton
        Left = 0
        Top = 768
        Width = 224
        Height = 89
        Align = alBottom
        Caption = 'Fechar'
        TabOrder = 0
        Flat = True
        StyleFamily = 'Angular-Dark'
        StyleClass = 'Warn'
        StyleAppearance = 'Raised'
        ExplicitTop = 680
      end
      object StyledButton1: TStyledButton
        Left = 0
        Top = 0
        Width = 224
        Height = 89
        Align = alTop
        Caption = 'Filmes'
        TabOrder = 1
        Flat = True
        StyleFamily = 'Bootstrap'
        StyleClass = 'Success'
        ExplicitTop = -6
      end
      object StyledButton2: TStyledButton
        Left = 0
        Top = 89
        Width = 224
        Height = 89
        Align = alTop
        Caption = 'S'#233'ries'
        TabOrder = 2
        Flat = True
        StyleFamily = 'Angular-Light'
        StyleClass = 'DeepPurple'
        ExplicitTop = 584
      end
      object StyledButton3: TStyledButton
        Left = 0
        Top = 178
        Width = 224
        Height = 89
        Align = alTop
        Caption = 'Animes'
        TabOrder = 3
        Flat = True
        StyleFamily = 'Angular-Dark'
        StyleClass = 'Blue-gray'
      end
    end
  end
end
